### ISSUE TITLE
RTT_DIR on OS/X

### ISSUE THREAD

**Issue by paultanner** [anlif/rtt_minimal#1]
I have installed JLink_MacOSX_V600g on OS/X El Capitan.
What would be the correct setting for RTT_DIR in this case?
(Looking at your Makefile I see "RTT_Implementation..." but I have no such folder.)
Thx.

**Comment by anlif** [comment]
Download the RTT files from: http://download.segger.com/J-Link/RTT/RTT_Implementation_141217.zip

This is the RTT implementation that will run on the microcontroller. The JLink software that you have downloaded are programs that will run on your computer.

**Comment by paultanner** [comment]
Great. Many thx for this. Works perfectly :-)
